language: go

env:
  - COVERALLS_TOKEN=EShYbHhNxrURLtYJCyCdP2AhDh63o0dzw

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/modocache/gover
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/{gosimple,staticcheck}
  - go get github.com/client9/misspell/cmd/misspell

script:
  - make check
  - make test-verbose
  - ./coveralls.bash

go:
  - 1.9.x
  - 1.10.x
  - tip
